# Generated by Django 3.1.6 on 2021-04-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
